# Generated by Django 3.0.6 on 2020-07-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20200531_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='API_KEY',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='APP_ID',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='SECRET_KEY',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
