# Generated by Django 3.0.6 on 2020-07-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20200707_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='API_KEY',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='APP_ID',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='SECRET_KEY',
        ),
    ]
