# Generated by Django 3.0.5 on 2020-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200501_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='player', max_length=16),
        ),
    ]
