# Generated by Django 3.0.6 on 2020-05-31 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle', '0001_initial'),
        ('guild', '0009_auto_20200528_0004'),
        ('user', '0011_auto_20200525_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('finish', models.DateField(blank=True, null=True)),
                ('desc', models.BooleanField(default='', max_length=32)),
                ('round', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='battle.Battle')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='battle.Boss')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='guild.Guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='user.User')),
            ],
        ),
    ]
