# Generated by Django 3.0.6 on 2020-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='desc',
            field=models.CharField(default='', max_length=32),
        ),
    ]
