# Generated by Django 3.0.6 on 2020-06-03 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200601_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 20, 3, 49, 744749)),
        ),
    ]
