# Generated by Django 3.0.6 on 2020-07-07 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 23, 41, 41, 140)),
        ),
    ]
