# Generated by Django 3.0.6 on 2020-07-07 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200707_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 0, 16, 2, 255932)),
        ),
    ]
