# Generated by Django 3.0.6 on 2020-05-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(default='1d743bd89b1511ea8f10d46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
