# Generated by Django 3.0.6 on 2020-05-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_auto_20200521_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(default='48ae6f289b1611ea9cadd46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
