# Generated by Django 3.0.6 on 2020-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_auto_20200521_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(default='118b21869b1811eaae74d46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='join',
            field=models.IntegerField(choices=[(0, 'Auto'), (1, 'Password'), (2, 'Validate'), (3, 'Forbid')], default=2),
        ),
    ]
