# Generated by Django 3.0.6 on 2020-05-22 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200521_1203'),
        ('guild', '0004_auto_20200521_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(default='d9d21fc29bdb11ea807ed46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='guild.Guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user.User')),
            ],
        ),
    ]
