# Generated by Django 3.0.6 on 2020-05-22 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0005_auto_20200522_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(default='952976929bde11ea95aad46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
