# Generated by Django 3.0.6 on 2020-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_auto_20200522_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.CharField(default='f760447a9c0e11eaa8aad46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(default='f7601e649c0e11eabba2d46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
