# Generated by Django 3.0.6 on 2020-05-25 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0007_auto_20200522_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='desc',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
