# Generated by Django 3.0.6 on 2020-05-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0008_auto_20200525_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='reason',
        ),
        migrations.AlterField(
            model_name='application',
            name='desc',
            field=models.CharField(max_length=32),
        ),
    ]
