# Generated by Django 3.0.6 on 2020-05-30 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_auto_20200525_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('rank', models.IntegerField(default=1)),
                ('star', models.IntegerField(default=1)),
                ('exclusive', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='user.User')),
            ],
        ),
    ]
