# Generated by Django 3.0.6 on 2020-05-20 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=16)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('qq', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
