# Generated by Django 3.0.6 on 2020-05-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
        ('user', '0003_auto_20200520_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='guild.Guild'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='8cb6a4069b1111ea9d36d46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
