# Generated by Django 3.0.6 on 2020-05-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200521_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='1d73efdc9b1511ea91f9d46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
