# Generated by Django 3.0.6 on 2020-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200521_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='11890d429b1811eabf84d46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
