# Generated by Django 3.0.6 on 2020-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200522_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='f75c65249c0e11ea8682d46d6df5224b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
